---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo
  vars:
    # yamllint disable-line rule:line-length
    openjdk10_checksum: 'sha256:f3b26abc9990a0b8929781310e14a339a7542adfd6596afb842fa0dd7e3848b2'
    # yamllint disable-line rule:line-length
    openjdk10_url: https://download.java.net/java/GA/jdk10/{{openjdk10_version}}/19aef61b38124481863b1413dce1855f/13/openjdk-{{openjdk10_version}}_linux-x64_bin.tar.gz
    openjdk10_version: 10.0.2
    # yamllint disable-line rule:line-length
    openjdk11_checksum: 'sha256:3784cfc4670f0d4c5482604c7c513beb1a92b005f569df9bf100e8bef6610f2e'
    # yamllint disable-line rule:line-length
    openjdk11_url: https://download.java.net/java/ga/jdk11/openjdk-{{openjdk11_version}}_linux-x64_bin.tar.gz
    openjdk11_version: 11

  pre_tasks:
    - include_role: name=lfit.system-update

  roles:
    - lfit.mono-install

  tasks:
    - name: 'Install OpenJDK {{openjdk10_version}}'
      block:
        # yamllint disable-line rule:line-length
        - name: 'Fetch OpenJDK {{openjdk10_version}} to /tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
          get_url:
            url: "{{openjdk10_url}}"
            dest: '/tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
            checksum: '{{openjdk10_checksum}}'
        - name: 'Untar OpenJDK {{openjdk10_version}} in /opt/'
          unarchive:
            src: '/tmp/jdk-{{openjdk10_version}}_linux-x64_bin.tar.gz'
            dest: /opt/
            mode: 0755
            remote_src: true
          become: true
        # yamllint disable rule:line-length
        - name: 'Setup Java master and slave links for OpenJDK {{openjdk10_version}}'
          command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-{{openjdk10_version}}/bin/java" 10 \
                    --slave "/usr/bin/jar" "jar" "/opt/jdk-{{openjdk10_version}}/bin/jar" \
                    --slave "/usr/bin/jarsigner" "jarsigner" "/opt/jdk-{{openjdk10_version}}/bin/jarsigner" \
                    --slave "/usr/bin/javac" "javac" "/opt/jdk-{{openjdk10_version}}/bin/javac" \
                    --slave "/usr/bin/javadoc" "javadoc" "/opt/jdk-{{openjdk10_version}}/bin/javadoc" \
                    --slave "/usr/bin/javah" "javah" "/opt/jdk-{{openjdk10_version}}/bin/javah" \
                    --slave "/usr/bin/javap" "javap" "/opt/jdk-{{openjdk10_version}}/bin/javap" \
                    --slave "/usr/bin/javaws" "javaws" "/opt/jdk-{{openjdk10_version}}/bin/javaws"'
          # yamllint enable rule:line-length
          become: true
    - name: 'Install OpenJDK {{openjdk11_version}}'
      block:
        # yamllint disable-line rule:line-length
        - name: 'Fetch OpenJDK 11 to /tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
          get_url:
            url: "{{openjdk11_url}}"
            dest: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
            checksum: '{{openjdk11_checksum}}'
        - name: 'Untar OpenJDK {{openjdk11_version}} in /opt/'
          unarchive:
            src: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
            dest: /opt/
            mode: 0755
            remote_src: true
          become: true
        # yamllint disable rule:line-length
        - name: 'Setup Java master and slave links for OpenJDK {{openjdk11_version}}'
          command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-{{openjdk11_version}}/bin/java" 10 \
                    --slave "/usr/bin/jar" "jar" "/opt/jdk-{{openjdk11_version}}/bin/jar" \
                    --slave "/usr/bin/jarsigner" "jarsigner" "/opt/jdk-{{openjdk11_version}}/bin/jarsigner" \
                    --slave "/usr/bin/javac" "javac" "/opt/jdk-{{openjdk11_version}}/bin/javac" \
                    --slave "/usr/bin/javadoc" "javadoc" "/opt/jdk-{{openjdk11_version}}/bin/javadoc" \
                    --slave "/usr/bin/javah" "javah" "/opt/jdk-{{openjdk11_version}}/bin/javah" \
                    --slave "/usr/bin/javap" "javap" "/opt/jdk-{{openjdk11_version}}/bin/javap" \
                    --slave "/usr/bin/javaws" "javaws" "/opt/jdk-{{openjdk11_version}}/bin/javaws"'
          # yamllint enable rule:line-length
          become: true

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
