---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: 'Install FD.io Required 16.04 Packages'
      apt:
        name:
          - gdb
          - gdbserver
          - bridge-utils
          - texlive-fonts-recommended
          - tex-common
          - texlive-base
          - texlive-binaries
          - texlive-pictures
          - texlive-latex-recommended
          - preview-latex-style
          - texlive-latex-extra
          - cloud-initramfs-growroot
          - cloud-initramfs-rescuevol
          - libmysqlclient-dev
          - doxygen
          - python-pyparsing
          - asciidoc
          - dblatex
          - source-highlight
          - lcov
          - gcc-multilib
          - bison
          - ccache
          - dkms
          - libganglia1-dev
          - libapr1-dev
          - libconfuse-dev
          - exuberant-ctags
          - cscope
          - indent
          - emacs
          - libxslt-dev
          - bc
          - linux-image-extra-virtual
          - google-mock
          - debian-xcontrol
          - pristine-tar
          - python-sphinx
          - python-scapy
          - inkscape
          - python-sphinx-rtd-theme
          - python3-sphinx
          - libnuma-dev
          - libibverbs-dev
          - ruby-dev
          - zip
        state: present
      # yamllint disable-line rule:line-length
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
      become: true

    - name: 'Install FD.io Required 18.04 Packages'
      apt:
        name:
          - gdb
          - gdbserver
          - bridge-utils
          - texlive-fonts-recommended
          - tex-common
          - texlive-base
          - texlive-binaries
          - texlive-pictures
          - texlive-latex-recommended
          - preview-latex-style
          - texlive-latex-extra
          - cloud-initramfs-growroot
          - cloud-initramfs-rescuevol
          - libmysqlclient-dev
          - doxygen
          - python-pyparsing
          - asciidoc
          - dblatex
          - source-highlight
          - lcov
          - bison
          - ccache
          - dkms
          - libganglia1-dev
          - libapr1-dev
          - libconfuse-dev
          - exuberant-ctags
          - cscope
          - indent
          - emacs
          - libxslt-dev
          - bc
          - linux-image-extra-virtual
          - google-mock
          - debian-xcontrol
          - pristine-tar
          - python-sphinx
          - python-scapy
          - inkscape
          - python-sphinx-rtd-theme
          - python3-sphinx
          - libnuma-dev
          - libibverbs-dev
          - ruby-dev
          - zip
          - libevent-dev
          - libboost-system-dev
          - libcurl4-openssl-dev
          - libboost-regex-dev
          - libboost-filesystem-dev
          - git-core
          - libqtav-dev
          - libavcodec-dev
          - libavformat-dev
          - libswscale-dev
          - libavresample-dev
        state: present
      # yamllint disable-line rule:line-length
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
      become: true

    - name: 'Install FD.io Required CentOS 7 Packages'
      yum:
        name:
          - apr-devel
          - asciidoc
          - autoconf
          - ccache
          - dblatex
          - dkms
          - epel-rpm-macros
          - ganglia-devel
          - glibc-static
          - kernel-devel
          - libcap-devel
          - libconfuse-devel
          - libconfuse-devel
          - python-sphinx
          - redhat-lsb
          - ruby-devel
          - scapy
          - source-highlight
          - valgrind
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: 'Install rake gem'
      command: 'gem install rake'
      become: true

    - name: 'Install PackageCloud'
      command: 'gem install package_cloud'
      become: true

  roles:
    - lfit.mono-install

  post_tasks:
    - name: System Reseal
      script: ../common-packer/provision/system-reseal.sh
      become: true
