---
##############################################################################
### Pipelines
##############################################################################

pipelines:
  - name: check
    source: gerrit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: draft-published
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
  - name: check-novote
    source: gerrit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: draft-published
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    success:
      gerrit: {}
    failure:
      gerrit: {}
  # - name: gate
  #   source: gerrit
  #   manager: DependentPipelineManager
  #   trigger:
  #     gerrit:
  #       - event: comment-added
  #         approval:
  #           - approved: 1
  #   success:
  #     gerrit:
  #       verified: 1
  #   failure:
  #     gerrit:
  #       verified: -1
  - name: periodic-daily
    source: gerrit
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '0 0 * * *'
  - name: periodic-weekly
    source: gerrit
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '0 0 * * 0'
  - name: post-merge
    source: gerrit
    manager: IndependentPipelineManager
    success-message: Build succeeded (check merge)
    failure-message: Build failed (check merge)
    trigger:
      gerrit:
        - event: change-merged
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(remerge)
    success:
      gerrit: {}
    failure:
      gerrit: {}
  - name: csit-manual-perf
    source: gerrit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(hw-perf-check)
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

##############################################################################
### Project Templates
##############################################################################

project-templates:
  - name: default-jobs
    check:
      - '{name}-verify'
    post-merge:
      - '{name}-merge'

##############################################################################
### Projects
##############################################################################

projects:
  - name: ci-management
    check:
      - ci-management-verify-jjb
      - ci-management-verify-zuul
      - ci-management-verify-nodepool
    post-merge:
      - ci-management-merge-jjb
      - ci-management-merge-zuul
      - ci-management-merge-nodepool

  - name: csit
#    csit-manual-perf:
#      - csit-vpp-functional-hw-tb2
    check:
#      - csit-vpp-functional-virl
      - csit-vpp-functional-nodepool

#  - name: honeycomb
#    template:
#      - name: default-jobs

  - name: vpp
    check-novote:
      - vpp-csit-verify-virl

