##############################################################################
### Pipelines
##############################################################################

pipelines:
  - name: check
    source: gerrit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: draft-published
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
  # - name: gate
  #   source: gerrit
  #   manager: DependentPipelineManager
  #   trigger:
  #     gerrit:
  #       - event: comment-added
  #         approval:
  #           - approved: 1
  #   success:
  #     gerrit:
  #       verified: 1
  #   failure:
  #     gerrit:
  #       verified: -1
  - name: periodic-daily
    source: gerrit
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '0 0 * * *'
  - name: periodic-weekly
    source: gerrit
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '0 0 * * 0'
  - name: post-merge
    source: gerrit
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: change-merged
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(remerge)
    success:
      gerrit:
        force-message: True
    failure:
      gerrit:
        force-message: True

##############################################################################
### Project Templates
##############################################################################

project-templates:
  - name: default-jobs
    check:
     - '{name}-verify'
    post-merge:
     - '{name}-merge'

##############################################################################
### Projects
##############################################################################

projects:
  - name: ci-management
    check:
      - ci-management-verify-jjb
    periodic-weekly:
      - ci-management-weekly
    post-merge:
      - ci-management-merge

  - name: csit
    check:
      - csit-vpp-bridge-domain

  - name: honeycomb
    template:
      - name: default-jobs

  - name: toolchain_test
    template:
      - name: default-jobs

  - name: vpp
    template:
      - name: default-jobs
