#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

BUILD_TOOLS="build-essential cmake"
LIBSSL_LIBEVENT="libevent-dev libssl-dev"
LONGBOW_DEPS=""
LIBPARC_DEPS="longbow $LIBSSL_LIBEVENT"
LIBCCNX_COMMON_DEPS="$LIBPARC_DEPS libparc"
LIBCCNX_TRANSPORT_RTA_DEPS="$LIBCCNX_COMMON_DEPS libccnx-common"
LIBCCNX_PORTAL_DEPS="$LIBCCNX_TRANSPORT_RTA_DEPS libccnx-transport-rta"
LIBICNET_DEPS="$LIBCCNX_PORTAL_DEPS libboost-system-dev"
METIS_DEPS="$LIBCCNX_TRANSPORT_RTA_DEPS libccnx-transport-rta"
HTTP_SERVER_DEPS="$LIBICNET_DEPS libicnet libboost-regex-dev libboost-filesystem-dev"