# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 sts=2 et :

# See ci-management/vagrant/lib/respin-functions.sh for examples of
# environment variable settings

require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|

  config.vm.provider :openstack do |os, override|

    # CPPROJECT=fdio
    # STACK_PROVIDER=vexxhost
    # STACK_PORTAL=secure.${STACK_PROVIDER}.com
    # STACK_ID_SERVER=auth.${STACK_PROVIDER}.net

    # OPENSTACK_AUTH_URL="https://${STACK_ID_SERVER}/v2.0/"
    # OPENSTACK_FLAVOR='v1-standard-4'
    # STACK_REGION_NAME='ca-ymq-1'
    # AVAILABILITY_ZONE='ca-ymq-2'

    os.openstack_auth_url = ENV['OPENSTACK_AUTH_URL']
    os.flavor             = ENV['OPENSTACK_FLAVOR']
    os.region             = ENV['STACK_REGION_NAME']
    os.availability_zone  = ENV['AVAILABILITY_ZONE']

    # https://${STACK_PORTAL}/console/#/account/credentials
    os.tenant_name = ENV['OS_TENANT_NAME']
    os.username    = ENV['OS_USERNAME']
    os.password    = ENV['OS_PASSWORD']

    # NETID=$(nova network-list | awk '/${CPPROJECT}/ {print $2}')
    os.networks    = ENV['NETID']

    # personal default instance names: for example, ${USER}-vagrant
    os.server_name = ENV['SERVER_NAME']
  end
end
