# packagecloud.io promote script
# This script will promote packages from the packagecloud.io staging repository
# to the packagecloud.io release repository

# package_cloud promote username/myrepo/[distro/version] packagename.ext username/destination_repo
#
# Add staging repo variable = to username/myrepo/[distro/version]
#  example:  https://packagecloud.io/fdio/staging
#  need to create a packagecloud staging repository
#
# Add release repo variable = to username/destination_repo
#  example:  https://packagecloud.io/fdio/release
#  need to create a packagecloud release repository
#
# Add packagename variable = to packagename.ext generated by find files?
#   RPMS=$(find . -type f -iregex '.*/.*\.\(s\)?rpm')
#   DEBS=$(find . -type f -iname '*.deb') - need to be able to specify the version
#   example:  17.01-release.x86_64 and 17.01-release_amd64
