# -*- mode: ruby -*-
# vi: set ts=2 sw=2 sts=2 et ft=ruby :

Vagrant.configure(2) do |config|
   # root off of the rackspace provider dummy box
  config.vm.box = "dummy"

  # rackspace systems even with cloud-init
  # don't seem to have the cloud init user ${osname}
  # getting the ssh key for some reason, root does
  # so use that
  config.ssh.username = 'root'

  # Fedora and EL systems default to requiring a tty for sudo
  if (ENV['RSPTY'] == 'default')
    config.ssh.pty = false
  else
    config.ssh.pty = true
  end

  # The rackspace provider by default tries to rsync
  # the local folder / vagrant box to /vagrant
  # unfortunately, even with config.ssh.pty = true
  # this fails because it doesn't recognize the pty requirement
  # when doing the sudo based rsync (not that it needs to sudo
  # when doing things as root). To avoid this, disable the
  # default sync, we don't need it anyway.
  config.vm.synced_folder '.', '/vagrant', :disabled => true

  config.vm.provider :openstack do |os, override|
    if ENV['RSIMAGE']
      os.image = ENV['RSIMAGE']
    else
      os.image = 'Ubuntu 14.04 LTS (2015-11-19) - Agentless'
    config.ssh.username = 'ubuntu'
  end

  # Do a full system update and force enforcing on (it's in permissive
  # by default in the rackspace base images)
  config.vm.provision 'shell', path: 'bootstrap.sh'

  # disable the default requiretty for sudo that Fedora and CentOS have
  config.vm.provision 'shell', path: 'remove_requiretty.sh'

  #################
  # FINAL CLEANUP #
  #################

  # set RESEAL to... anything if you want to snap an image of this box
  # not setting the environment variable will cause the system to come
  # up fully and not be in a resealable state
  if ENV['RESEAL']
    config.vm.provision 'shell', path: '../lib/system_reseal.sh'
  end
end
